### ISSUE TITLE
Chart repo address

### ISSUE THREAD

**Issue by hayorov** [lightbend/flink-operator#2]
Hello,

I cannot find the official help repo for the chart? Does it exist?

**Comment by yuchaoran2011** [comment]
@hayorov What do you mean by "help repo"? Did you mean documentation? The [README](https://github.com/lightbend/flink-operator/blob/master/README.md) file serves as the documentation. Feel free to let us know if you need any further help.

**Comment by yuchaoran2011** [comment]
@hayorov I see what you meant. You are talking about the Helm repo (the thing used for `helm repo add`). No we don't provide an official Helm repo at this moment. But we will consider it.

**Comment by hayorov** [comment]
@yuchaoran2011 thank you. Let me if I can help you with that I.e. setup that automation CI/CD for publishing a new version. Btw, what do you think about default hub.helm.sh/stable?

**Comment by pedro93** [comment]
Hello,

Is this repository no longer maintained? 
What is the status of this project and in particular of this issue?

If someone can be give me some pointers I can help publish this chart, as it is useful for me.

Thank you.

**Comment by andreaTP** [comment]
No, this is no longer maintained.
